name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    env:
      Projectname: GraphBuilder-npp
    strategy:
      fail-fast: false
      matrix:
        build_platform: [win64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: setup lazarus build env
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: "stable"
        with-cache: true

    - name: build of plugin dll
      working-directory: .\
      run: |
           cd ..
           git clone --branch v1.3.4 --depth 1 https://github.com/pisarev/pascal-mathparser.git
           git clone --branch v1.3.4 --depth 1 https://github.com/pisarev/pascal-crossgraph.git
           cd .\graphbuilder-npp
           git clone --branch 1.0.4078.44 https://github.com/salvadordf/WebView4Delphi.git
           $env:WEBVIEW4DELPHI = '.\WebView4Delphi'
           $env:LAZARUS_DIR = 'D:\a\_temp\installers\lazarus'
           .\build-lazarus.ps1

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: zip artifacts for Release ${{ matrix.build_platform }}
      run: |
           Remove-Item .\lazarus\bin\GraphBuilderLaz.dbg
           7z a ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip .\lazarus\bin\*

    - name: Archive artifacts for Release ${{ matrix.build_platform }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip
        path: ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip
